#!/bin/bash

set -e -u

DIR="$(dirname "$0")"
FILE_BASE="$DIR/../go-maps-backend"

function start_server() {
    (cd "$FILE_BASE"; while ! go build -o simple-offline-map *.go; do sleep 1; done)
    "$FILE_BASE"/simple-offline-map "$@" &
    PID=$!
    echo "go server started ($PID)"
}

function stop_server() {
    test -n "$PID" && kill "$PID" || true
    echo "Killed old server"
}

cd "$FILE_BASE/.."

start_server "$@"

trap stop_server INT

while inotifywait -q -e modify -r "$FILE_BASE"; do
    echo "changes detected; restarting node server ($PID)"
    stop_server
    sleep 0.5
    date
    start_server "$@"
done

